name: project_environment
channels:
- defaults
- pytorch
dependencies:
- python=3.6.8
- pip=20.2
- pytorch=1.5.0
- torchvision=0.6.0
- pip:
  - azureml-defaults
  - azureml-dataprep>=1.6
  - pandas==0.25.3
  - numpy==1.18.1
  - pyarrow==0.16.0
  - scikit-learn==0.22.2
  - nltk==3.4
  - matplotlib==3.1.0