name: imagekeras_train_conda_env
channels:
  - defaults
dependencies:
  - python=3.6.2
  - pip:
      - azureml-mlflow
      - azureml-dataset-runtime
      - keras==2.4.3
      - tensorflow==2.4.3
      - numpy
      - scikit-learn
      - pandas
      - matplotlib
      - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/test-sdk-cli-v2
      - azure-ml==0.0.59355733
