# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: project_environment
channels:
  - defaults
dependencies:
  - python=3.6.8
  - pip=20.0
  - pip:
    - azureml-defaults
    - azureml-dataprep>=1.6